# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push]

jobs:
  run-all-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.4.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.4.0
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.yarn 
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-
          ${{ runner.OS }}-
    - name: Install node dependencies
      run: yarn install
    - name: Run ESLint
      run: yarn run lint
    - name: Run Typescript typechecking
      run: yarn run typecheck
    - name: Run Tests
      run: yarn test 
